export const customLocations = [
    {
        airportId: '99999',
        name: 'La Balsa',
        city: 'La Balsa',
        country: 'Ecuador',
        iata: 'LBZ-XBORDER',
        lat: '-4.873',
        lng: '-79.213',
        alt: '715',
        timezone: '\\N',
        dst: '\\N',
        tz: '\\N',
        type: 'border-crossing',
        source: 'custom',
        note: 'Road-only Ecuador–Peru border crossing, no airport',
    },
];

const page1 = [];

const page2 = [];

const page3 = [];

const page4 = [
    {
        id: 12,
        date: '2007-05-17',
        departure: {
            time: '07:30',
            airport_code: 'NUE',
            city: 'Nürnberg',
            country: 'Deutschland',
            airport_name: 'Flughafen Nürnberg',
        },
        arrival: {
            time: '08:25',
            airport_code: 'DUS',
            city: 'Düsseldorf',
            country: 'Deutschland',
            airport_name: 'Düsseldorf',
        },
        distance_km: '365',
        duration: '0:55',
        airline: 'Air Berlin',
        flight_number: 'AB6771',
        aircraft: '',
    },
    {
        id: 11,
        date: '2007-03-01',
        departure: {
            time: '13:40',
            airport_code: 'DUS',
            city: 'Düsseldorf',
            country: 'Deutschland',
            airport_name: 'International',
        },
        arrival: {
            time: '14:40',
            airport_code: 'NUE',
            city: 'Nürnberg',
            country: 'Deutschland',
            airport_name: 'Nürnberg',
        },
        distance_km: '365',
        duration: '1:00',
        airline: 'dba',
        flight_number: 'DI7764',
        aircraft: '',
    },
    {
        id: 10,
        date: '2007-03-01',
        departure: {
            time: '07:30',
            airport_code: 'LHR',
            city: 'London',
            country: 'Großbritannien',
            airport_name: 'Heathrow',
        },
        arrival: {
            time: '09:50',
            airport_code: 'DUS',
            city: 'Düsseldorf',
            country: 'Deutschland',
            airport_name: 'Düsseldorf',
        },
        distance_km: '502',
        duration: '1:20',
        airline: 'British Airways',
        flight_number: 'BA936',
        aircraft: '',
    },
    {
        id: 9,
        date: '2007-03-01',
        departure: {
            time: '01:10',
            airport_code: 'HKG',
            city: 'Hongkong',
            country: 'China',
            airport_name: 'Chek Lap Kok',
        },
        arrival: {
            time: '06:20',
            airport_code: 'LHR',
            city: 'London',
            country: 'Großbritannien',
            airport_name: 'London',
        },
        distance_km: '9,641',
        duration: '13:10',
        airline: 'British Airways',
        flight_number: 'BA28',
        aircraft: '',
    },
    {
        id: 8,
        date: '2006-12-24',
        departure: {
            time: '20:25',
            airport_code: 'LHR',
            city: 'London',
            country: 'Großbritannien',
            airport_name: 'Heathrow',
        },
        arrival: {
            time: '16:10 +1',
            airport_code: 'HKG',
            city: 'Hongkong',
            country: 'China',
            airport_name: 'Hongkong',
        },
        distance_km: '9,641',
        duration: '11:45',
        airline: 'British Airways',
        flight_number: 'BA31',
        aircraft: '',
    },
    {
        id: 7,
        date: '2006-12-24',
        departure: {
            time: '14:15',
            airport_code: 'DUS',
            city: 'Düsseldorf',
            country: 'Deutschland',
            airport_name: 'International',
        },
        arrival: {
            time: '14:40',
            airport_code: 'LHR',
            city: 'London',
            country: 'Großbritannien',
            airport_name: 'London',
        },
        distance_km: '502',
        duration: '1:25',
        airline: 'British Airways',
        flight_number: 'BA933',
        aircraft: '',
    },
    {
        id: 6,
        date: '',
        departure: {
            time: '',
            airport_code: 'DUB',
            city: 'Dublin',
            country: 'Irland',
        },
        arrival: {
            time: '',
            airport_code: 'CRL',
            city: 'Brüssel',
            country: 'Belgien',
            airport_name: 'Brüssel',
        },
        distance_km: '805',
        duration: '1:24',
        airline: 'Ryanair',
        flight_number: '',
        aircraft: '',
    },
    {
        id: 5,
        date: '',
        departure: {
            time: '',
            airport_code: 'CRL',
            city: 'Brüssel',
            country: 'Belgien',
            airport_name: 'Charleroi',
        },
        arrival: {
            time: '',
            airport_code: 'DUB',
            city: 'Dublin',
            country: 'Irland',
            airport_name: 'Dublin',
        },
        distance_km: '805',
        duration: '1:24',
        airline: 'Ryanair',
        flight_number: '',
        aircraft: '',
    },
];

const roadTrips = [];

export const flights = [...page1, ...page2, ...page3, ...page4/*, ...roadTrips}*/];
